vich_uploader:
  db_driver: orm

  mappings:
    media_object:
      uri_prefix: /media
      upload_destination: "%kernel.project_dir%/public/media"
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer

    user_image:
      uri_prefix: images/users
      upload_destination: "%kernel.project_dir%/public/images/users"
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer
